// Real OpenLibrary subject arrays pulled from openlibrary.org work JSON endpoints.
// Kept verbatim as shipped by OL at fetch time. Reusable by Phase 4 enrichment tests.
// Source: https://openlibrary.org/works/<key>.json
//
// Last fetched: 2026-04-23.

// Foundation by Isaac Asimov - OL46125W
export const FOUNDATION_SUBJECTS: readonly string[] = [
  'Psychohistory',
  'Open Library Staff Picks',
  'Life on other planets',
  'Fiction',
  'Science Fiction',
  'Long Now Manual for Civilization',
  'Prophecy',
  'Historians',
  'Robots',
  'Fiction, science fiction, general',
  'American literature',
  'American Fantasy fiction',
  'Vie extraterrestre',
  'Romans, nouvelles',
  'Psychohistoire',
  'Psychological fiction',
  'American Science fiction',
  'Hari Seldon (Fictitious character)',
];

// The Fellowship of the Ring / The Lord of the Rings by J.R.R. Tolkien - OL27448W
export const LOTR_SUBJECTS: readonly string[] = [
  'The Lord of the Rings',
  'Fiction',
  'Ficción',
  'English Fantasy fiction',
  'Fantasy fiction',
  'Open Library Staff Picks',
  'Middle Earth (Imaginary place)',
  'Fiction, fantasy, epic',
  'Middle earth (imaginary place), fiction',
  'Baggins, frodo (fictitious character), fiction',
  'Gandalf (fictitious character), fiction',
  'British and irish fiction (fictional works by one author)',
  'English literature',
  'Frodo Baggins (Fictitious character)',
  'Fiction, fantasy, general',
  'English language',
  'Fiction, media tie-in',
  'Gift books',
  'Quests (Expeditions)',
  'Wizards',
  'Telephone directories',
];

// A Court of Mist and Fury by Sarah J. Maas - OL17784315W
export const ACOMAF_SUBJECTS: readonly string[] = [
  'Fantasy',
  'Fiction',
  'Fairies',
  'Blessing and cursing',
  'Fantasy fiction',
  'Fairies, fiction',
  'nyt:young-adult-hardcover=2016-05-22',
  'New York Times bestseller',
  'nyt:young-adult-e-book=2016-05-22',
  'collectionID:TexChallenge2021',
  'collectionID:KellerChallenge',
  'collectionID:EanesChallenge',
  'collectionID:AlpineChallenge',
  'Adaptations',
  'Magic',
  'Courts and courtiers',
  'Fantasy & Magic',
  'Love & Romance',
  'Action & Adventure',
  'General',
  'series:A_Court_of_Thorns_and_Roses',
  "Children's fiction",
];

// The Martian by Andy Weir - OL17091839W
export const MARTIAN_SUBJECTS: readonly string[] = [
  'Science-Fiction',
  'Science Fiction & Fantasy',
  'Suspense & Thriller',
  'Science fiction',
  'Amerikanisches Englisch',
  'Astronauts',
  'Survival',
  'Fiction',
  'Survival skills',
  'Supervivencia',
  'Novela',
  'Astronautas',
  'Reading Level-Grade 7',
  'Reading Level-Grade 9',
  'Reading Level-Grade 8',
  'Reading Level-Grade 11',
  'Reading Level-Grade 10',
  'Reading Level-Grade 12',
  'Fiction, science fiction, action & adventure',
  'Fiction, science fiction, general',
  'Large type books',
  'Arabic language materials',
  'Romans, nouvelles',
  'nyt:hardcover-fiction=2014-03-02',
  'New York Times bestseller',
  'Chang pian xiao shuo',
  "Children's fiction",
  'Adventure and adventurers, fiction',
  'Fantasy fiction',
];

// Mistborn: The Final Empire by Brandon Sanderson - OL5738148W
export const MISTBORN_SUBJECTS: readonly string[] = [
  'form:novel',
  'series:The Mistborn Saga',
  'series:Mistborn Original Trilogy',
  'genre:high fantasy',
  'Courts and courtiers',
  'Women revolutionaries',
  'Fiction',
  'Adventure',
  'Magic',
  'Thieves',
  'Nobility',
  'Covert Operations',
  'Mystical powers',
  'Upraising',
  'Epic',
  'Good and evil',
  'Slaves',
  'Fantasía',
  'Ficción',
  'Magia',
  'Adulto',
];

// Sapiens: A Brief History of Humankind by Yuval Noah Harari - OL17075811W
export const SAPIENS_SUBJECTS: readonly string[] = [
  'Technology and civilization',
  'Human beings',
  'Historical Chronology',
  'Historia universal',
  'Historia',
  'Civilization',
  'Hombre',
  'World history',
  'History',
  'Non-Fiction',
  'Science',
  'SCIENCE / Life Sciences / General',
  'SCIENCE / General',
  'SCIENCE / Life Sciences / Evolution',
  'Weltgeschichte',
  'Civilization, history',
  'Chronology, historical',
  'Chronologie historique',
  'Technologie et civilisation',
  'Histoire universelle',
  'Histoire',
  'Humans',
  'Civilisation',
  'Homme',
  'nyt:combined-print-and-e-book-nonfiction=2015-03-01',
  'New York Times bestseller',
  'Life Sciences',
  'Evolution',
  'General',
  'Menschheit',
  'Humanité',
  'Människan',
  'Fysisk antropologi',
  'Human',
  'Sapiens',
  'nyt:paperback-nonfiction=2018-06-03',
  'Comics & graphic novels, adaptations',
  'Zivilisation',
  'Society',
  'Psychology',
  'Economic history',
  'Cognition and culture',
  'Civilization--history',
  'Human beings--history',
  'Technology and civilization--history',
  'Cb113.h4 h3713 2015',
  '599.9',
  'Sci027000 sci086000 sci000000',
  'Cronología histórica',
  'Tecnología y civilización',
  'Anthropology',
  'Long Now Manual for Civilization',
  'Comic books, strips',
];

// Thinking, Fast and Slow by Daniel Kahneman - OL15992072W
export const THINKING_FAST_SLOW_SUBJECTS: readonly string[] = [
  'Intuition',
  'Thought and thinking',
  'Reasoning',
  'Decision making',
  'New York Times bestseller',
  'Long Now Manual for Civilization',
  'Thinking',
  'Kognition',
  '77.32 intelligence, creativity',
  'New York Times reviewed',
  'Reason',
  'Cognition',
  'Self-actualization (Psychology)',
  'Cognitive psychology',
  'Psychology',
  'Schlussfolgern',
  'Entscheidungsfindung',
  'Priming',
  'Spiegel-Bestseller',
  'Verhaltensökonomie',
  'Zwei Systeme',
  '2970: Taschenbuch / Sachbücher/Politik, Gesellschaft, Wirtschaft',
  'Bf441 .k238 2011',
  '2012 a-186',
  'Bf 441',
  'Bf 441 k12 2011',
  '153.4/2',
  'Nyt:hardcover_business_books=2012-02-25',
  'Tankande',
  'Beslutsfattande',
  'Besliskunde',
  'Resonerande',
  'Psykologiska aspekter',
  'Emotions and cognition',
  'Tänkande',
];

// Dune by Frank Herbert - OL893415W
export const DUNE_SUBJECTS: readonly string[] = [
  'Dune (Imaginary place)',
  'Fiction',
  'Fiction, science fiction, general',
  'Dune (imaginary place), fiction',
  'New York Times reviewed',
  'Science fiction',
  'Science-fiction',
  'American literature',
  'nyt:mass-market-monthly=2021-11-07',
  'New York Times bestseller',
  'award:nebula_award=novel',
  'nyt:trade-fiction-paperback=2021-11-07',
  'Hugo Award Winner',
  'award:hugo_award=1966',
  'award:hugo_award=novel',
  'American Science fiction',
  'Long Now Manual for Civilization',
  'Ecology',
  'Fantasy fiction',
];

// Pride and Prejudice by Jane Austen - OL66554W
export const PRIDE_AND_PREJUDICE_SUBJECTS: readonly string[] = [
  'Fiction, Romance, Historical, Regency',
  'British and Irish fiction (fictional works by one author)',
  'Brothers and sisters',
  'Courtship',
  'Drama',
  'English fiction',
  'English literature',
  'Families',
  'Family',
  'Family life',
  'Family relations',
  'Fiction Classics',
  'History',
  'Interpersonal relations',
  'Literary Fiction',
  'Love stories',
  'manners',
  'Manners and customs',
  'marriage',
  'Sisters',
  'Social classes',
  'Social life and customs',
  'Upper class',
  'wealth',
  'Women in England',
  'young ladies',
  'Young women',
  'entail',
  'Young women, fiction',
  'Sisters, fiction',
  'Fiction, family life, general',
  'England, fiction',
  'Man-woman relationships, fiction',
  'Roman anglais',
  'Classes sociales',
  'Romans, nouvelles',
  'Sœurs',
  'Amours',
  'Jeunes femmes',
  'Familles',
  'Mœurs et coutumes"',
  'Clases sociales',
  'Novela',
  'Jóvenes (Mujeres)',
  'Cortejo amoroso',
  'Hermanas',
  'Cuentos de amor',
  'Fiction, coming of age',
  'Fiction, romance, general',
  'Great britain, social life and customs, fiction',
  'Readers',
  'Prejudices',
  'Romance fiction',
  'Historical fiction',
  'Classical literature',
  'Domestic fiction',
  'English language, textbooks for foreign speakers',
  'Women, fiction',
  'Adaptations',
  'Gentry',
  'Mate selection',
  'Fiction, romance, historical, general',
  'English literature (collections)',
  'Coloring books',
  'Fiction, family life',
  'Language and languages, study and teaching',
  'Emoticons',
  'Drama (dramatic works by one author)',
  'Feelings',
  'Class',
  'Englisch',
  'Roman',
  'Sociala klasser i litteraturen',
  'Prophecies',
  'Great britain',
  'Reading level-grade 7',
  'Reading level-grade 9',
  'Reading level-grade 8',
  'Reading level-grade 11',
  'Reading level-grade 10',
  'Reading level-grade 12',
  'Large type books',
  'Fiction, romance, historical',
  'Austen, jane, 1775-1817',
  'Literature and fiction (general)',
  'English literature, history and criticism',
  'England',
  'Художественная литература -- Великобритания -- Английская литература -- 1-ая пол. 19 в. -- Романы',
  'Novel',
  'Fiction',
  'Long Now Manual for Civilization',
  'Elizabeth Bennet (Fictitious character)',
  'Fitzwilliam Darcy (Fictitious character)',
  'Pride and prejudice (Austen, Jane)',
  'Mr. Collins (Fictitious character)',
];

// The Name of the Wind by Patrick Rothfuss - OL8479867W
export const NAME_OF_THE_WIND_SUBJECTS: readonly string[] = [
  'orphans',
  'American fantasy fiction',
  'Adult books for young adults',
  'epic fiction',
  'series',
  'Juvenile audience',
  'demons',
  'quests',
  'loss (psychology)',
  'fate and fatalism',
  'voyages and travels',
  'heroes and heroines',
  'murder',
  'rulers',
  'gods and goddesses',
  'imaginary places',
  'good and evil',
  'fantasy fiction',
  'The Kingkiller Chronicle',
  'fantasy',
  'assassins',
  'Quill Award winner',
  'Alex Award winner',
  'Magic',
  'Magician',
  'Wizards',
  'Fiction',
  'Magicians',
  'Magos',
  'Magia',
  'Asesinos',
  'Novela fantástica',
  'Ficción',
  'Homeless children',
  'Antiheroes',
  'Storytelling',
  'Legends',
  'Fiction, fantasy, epic',
  'nyt:mass-market-paperback=2015-01-04',
  'New York Times bestseller',
  'Fantasy Kingiller Chronicles',
  'Coming-of-age',
  'Adventure',
  'Music',
  'Mystery',
  'Revenge',
  'School',
  'Orphan',
  'Inn',
  'University',
  'Chandrian',
  'Kvothe',
  'Fiction, fantasy, general',
  'Novelas estadounidenses',
  'American literature',
];
